import { db } from '@/db';
import { activityLogs } from '@/db/schema';

async function main() {
    const sampleActivityLogs = [
        {
            userId: 1,
            userRole: 'admin',
            activityType: 'login',
            entityType: 'user',
            entityId: 1,
            description: 'Admin user logged in successfully',
            ipAddress: '197.210.70.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ loginMethod: 'pin', deviceType: 'desktop', location: 'Lagos' }),
            createdAt: new Date('2024-01-15T08:30:00Z').toISOString(),
        },
        {
            userId: 1,
            userRole: 'admin',
            activityType: 'verify',
            entityType: 'product',
            entityId: 1,
            description: 'Product verified: Premium Yellow Maize - 500kg batch',
            ipAddress: '197.210.70.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ productId: 1, productName: 'Premium Yellow Maize', quantity: 500, verificationStatus: 'approved' }),
            createdAt: new Date('2024-01-15T10:15:00Z').toISOString(),
        },
        {
            userId: 1,
            userRole: 'admin',
            activityType: 'assign',
            entityType: 'delivery',
            entityId: 1,
            description: 'Delivery task assigned to driver Yusuf Garba for Order ORD-2024-001',
            ipAddress: '197.210.70.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ orderId: 1, orderNumber: 'ORD-2024-001', driverId: 9, driverName: 'Yusuf Garba', route: 'Kano to Lagos' }),
            createdAt: new Date('2024-01-16T14:20:00Z').toISOString(),
        },
        {
            userId: 1,
            userRole: 'admin',
            activityType: 'verify',
            entityType: 'product',
            entityId: 3,
            description: 'Product verified: Fresh Tomatoes - Grade A quality',
            ipAddress: '105.112.45.89',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ productId: 3, productName: 'Fresh Tomatoes', quantity: 200, qualityGrade: 'A' }),
            createdAt: new Date('2024-01-18T09:45:00Z').toISOString(),
        },
        {
            userId: 1,
            userRole: 'admin',
            activityType: 'logout',
            entityType: 'user',
            entityId: 1,
            description: 'Admin user logged out successfully',
            ipAddress: '197.210.70.45',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ sessionDuration: '6 hours 30 minutes', actionsPerformed: 15 }),
            createdAt: new Date('2024-01-18T15:00:00Z').toISOString(),
        },
        {
            userId: 2,
            userRole: 'seller',
            activityType: 'login',
            entityType: 'user',
            entityId: 2,
            description: 'Seller Aminu Bello logged in via mobile app',
            ipAddress: '102.89.23.156',
            userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ loginMethod: 'pin', deviceType: 'mobile', location: 'Kano' }),
            createdAt: new Date('2024-01-12T07:00:00Z').toISOString(),
        },
        {
            userId: 2,
            userRole: 'seller',
            activityType: 'create',
            entityType: 'product',
            entityId: 1,
            description: 'New product listed: Premium Yellow Maize - 500kg available',
            ipAddress: '102.89.23.156',
            userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ productId: 1, productName: 'Premium Yellow Maize', quantity: 500, pricePerUnit: '250', totalPrice: '125000' }),
            createdAt: new Date('2024-01-12T07:30:00Z').toISOString(),
        },
        {
            userId: 3,
            userRole: 'seller',
            activityType: 'registration',
            entityType: 'user',
            entityId: 3,
            description: 'New seller registered: Fatima Ibrahim from Kaduna',
            ipAddress: '197.210.88.123',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
            metadata: JSON.stringify({ registrationType: 'seller', location: 'Kaduna', referralSource: 'social_media' }),
            createdAt: new Date('2024-01-10T11:20:00Z').toISOString(),
        },
        {
            userId: 3,
            userRole: 'seller',
            activityType: 'create',
            entityType: 'product',
            entityId: 3,
            description: 'New product listed: Fresh Tomatoes - 200 baskets available',
            ipAddress: '197.210.88.123',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
            metadata: JSON.stringify({ productId: 3, productName: 'Fresh Tomatoes', quantity: 200, pricePerUnit: '3500', totalPrice: '700000' }),
            createdAt: new Date('2024-01-13T09:15:00Z').toISOString(),
        },
        {
            userId: 4,
            userRole: 'seller',
            activityType: 'update',
            entityType: 'product',
            entityId: 2,
            description: 'Product updated: Reduced price for White Rice from ₦45,000 to ₦42,000 per bag',
            ipAddress: '105.112.67.234',
            userAgent: 'Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ productId: 2, oldPrice: '45000', newPrice: '42000', reason: 'market_adjustment' }),
            createdAt: new Date('2024-01-17T13:40:00Z').toISOString(),
        },
        {
            userId: 5,
            userRole: 'buyer',
            activityType: 'registration',
            entityType: 'user',
            entityId: 5,
            description: 'New buyer registered: Chinedu Okafor from Lagos',
            ipAddress: '197.210.45.78',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ registrationType: 'buyer', location: 'Lagos', businessType: 'retail' }),
            createdAt: new Date('2024-01-14T10:00:00Z').toISOString(),
        },
        {
            userId: 5,
            userRole: 'buyer',
            activityType: 'create',
            entityType: 'order',
            entityId: 1,
            description: 'Order ORD-2024-001 placed successfully - Total: ₦125,000 for 500kg Premium Yellow Maize',
            ipAddress: '197.210.45.78',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ orderId: 1, orderNumber: 'ORD-2024-001', amount: '125000', itemCount: 1, deliveryAddress: 'Oshodi Market, Lagos' }),
            createdAt: new Date('2024-01-15T11:30:00Z').toISOString(),
        },
        {
            userId: 5,
            userRole: 'buyer',
            activityType: 'payment',
            entityType: 'order',
            entityId: 1,
            description: 'Payment processed for order ORD-2024-001 via bank transfer - Amount: ₦125,000',
            ipAddress: '197.210.45.78',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ orderId: 1, orderNumber: 'ORD-2024-001', amount: '125000', paymentMethod: 'bank_transfer', escrowStatus: 'held' }),
            createdAt: new Date('2024-01-15T11:45:00Z').toISOString(),
        },
        {
            userId: 6,
            userRole: 'buyer',
            activityType: 'login',
            entityType: 'user',
            entityId: 6,
            description: 'Buyer Aisha Mohammed logged in from mobile device',
            ipAddress: '105.112.89.45',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
            metadata: JSON.stringify({ loginMethod: 'pin', deviceType: 'mobile', location: 'Abuja' }),
            createdAt: new Date('2024-01-19T08:15:00Z').toISOString(),
        },
        {
            userId: 7,
            userRole: 'buyer',
            activityType: 'complete',
            entityType: 'order',
            entityId: 1,
            description: 'Delivery completed and approved for order ORD-2024-001 - Buyer confirmed receipt',
            ipAddress: '197.210.45.78',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            metadata: JSON.stringify({ orderId: 1, orderNumber: 'ORD-2024-001', buyerRating: 5, deliveryTime: '2 days', condition: 'excellent' }),
            createdAt: new Date('2024-01-18T16:00:00Z').toISOString(),
        },
        {
            userId: 9,
            userRole: 'driver',
            activityType: 'login',
            entityType: 'user',
            entityId: 9,
            description: 'Driver Yusuf Garba logged in to check assigned deliveries',
            ipAddress: '102.89.56.123',
            userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ loginMethod: 'pin', deviceType: 'mobile', location: 'Kano' }),
            createdAt: new Date('2024-01-16T15:00:00Z').toISOString(),
        },
        {
            userId: 9,
            userRole: 'driver',
            activityType: 'update',
            entityType: 'delivery',
            entityId: 1,
            description: 'Delivery status updated to "in_transit" for order ORD-2024-001 - Picked up from Kano',
            ipAddress: '102.89.56.123',
            userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ deliveryId: 1, orderId: 1, status: 'in_transit', pickupTime: '2024-01-16T15:30:00Z', estimatedArrival: '2024-01-18T10:00:00Z' }),
            createdAt: new Date('2024-01-16T15:30:00Z').toISOString(),
        },
        {
            userId: 10,
            userRole: 'driver',
            activityType: 'complete',
            entityType: 'delivery',
            entityId: 1,
            description: 'Delivery completed for order ORD-2024-001 - Package delivered to Oshodi Market, Lagos',
            ipAddress: '197.210.123.89',
            userAgent: 'Mozilla/5.0 (Linux; Android 11; TECNO KE7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
            metadata: JSON.stringify({ deliveryId: 1, orderId: 1, deliveryTime: '2024-01-18T14:30:00Z', recipientSignature: 'captured', photos: 3 }),
            createdAt: new Date('2024-01-18T14:30:00Z').toISOString(),
        },
        {
            userId: null,
            userRole: 'system',
            activityType: 'payment',
            entityType: 'order',
            entityId: 1,
            description: 'Escrow funds released to seller - Order ORD-2024-001 completed successfully',
            ipAddress: '197.210.1.1',
            userAgent: 'AgriMarket-System/1.0',
            metadata: JSON.stringify({ orderId: 1, orderNumber: 'ORD-2024-001', amount: '125000', platformFee: '6250', logisticsFee: '12500', netAmount: '106250', sellerId: 2 }),
            createdAt: new Date('2024-01-18T16:15:00Z').toISOString(),
        },
        {
            userId: null,
            userRole: 'system',
            activityType: 'update',
            entityType: 'order',
            entityId: 2,
            description: 'Automated order cancellation - Payment timeout exceeded for order ORD-2024-002',
            ipAddress: '197.210.1.1',
            userAgent: 'AgriMarket-System/1.0',
            metadata: JSON.stringify({ orderId: 2, orderNumber: 'ORD-2024-002', reason: 'payment_timeout', timeoutDuration: '24 hours', refundStatus: 'not_applicable' }),
            createdAt: new Date('2024-01-20T10:00:00Z').toISOString(),
        },
    ];

    await db.insert(activityLogs).values(sampleActivityLogs);
    
    console.log('✅ Activity logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});