import { db } from '@/db';
import { deliveryTasks } from '@/db/schema';

async function main() {
    const sampleDeliveryTasks = [
        {
            orderId: 1,
            driverId: 9,
            sellerId: 2,
            pickupAddress: '45 Awolowo Road, Ikoyi, Lagos',
            deliveryAddress: '12 Admiralty Way, Lekki Phase 1, Lagos',
            pickupContactName: 'Adebayo Fashola',
            pickupContactPhone: '+2348012345678',
            deliveryContactName: 'Chioma Okafor',
            deliveryContactPhone: '+2348098765432',
            status: 'delivered',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task1_photo1.jpg',
                'https://storage.example.com/pickup/task1_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_001_ABC123',
            pickupVerifiedAt: '2024-01-15T10:30:00Z',
            deliverySignature: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
            deliveryPhotos: JSON.stringify([
                'https://storage.example.com/delivery/task1_photo1.jpg',
                'https://storage.example.com/delivery/task1_photo2.jpg'
            ]),
            deliveryVerifiedAt: '2024-01-15T14:45:00Z',
            createdAt: '2024-01-15T09:00:00Z',
            updatedAt: '2024-01-15T14:45:00Z',
        },
        {
            orderId: 2,
            driverId: 10,
            sellerId: 3,
            pickupAddress: '23 Zoo Road, Kano Municipal, Kano',
            deliveryAddress: '78 Independence Way, Kaduna North, Kaduna',
            pickupContactName: 'Ibrahim Musa',
            pickupContactPhone: '+2348023456789',
            deliveryContactName: 'Fatima Hassan',
            deliveryContactPhone: '+2348087654321',
            status: 'delivered',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task2_photo1.jpg',
                'https://storage.example.com/pickup/task2_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_002_DEF456',
            pickupVerifiedAt: '2024-01-16T11:15:00Z',
            deliverySignature: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
            deliveryPhotos: JSON.stringify([
                'https://storage.example.com/delivery/task2_photo1.jpg',
                'https://storage.example.com/delivery/task2_photo2.jpg'
            ]),
            deliveryVerifiedAt: '2024-01-16T16:20:00Z',
            createdAt: '2024-01-16T09:30:00Z',
            updatedAt: '2024-01-16T16:20:00Z',
        },
        {
            orderId: 3,
            driverId: 9,
            sellerId: 4,
            pickupAddress: '67 Ring Road, Challenge, Ibadan',
            deliveryAddress: '34 Allen Avenue, Ikeja, Lagos',
            pickupContactName: 'Olusegun Adeyemi',
            pickupContactPhone: '+2348034567890',
            deliveryContactName: 'Ngozi Eze',
            deliveryContactPhone: '+2348076543210',
            status: 'delivered',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task3_photo1.jpg',
                'https://storage.example.com/pickup/task3_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_003_GHI789',
            pickupVerifiedAt: '2024-01-17T08:45:00Z',
            deliverySignature: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
            deliveryPhotos: JSON.stringify([
                'https://storage.example.com/delivery/task3_photo1.jpg',
                'https://storage.example.com/delivery/task3_photo2.jpg'
            ]),
            deliveryVerifiedAt: '2024-01-17T15:30:00Z',
            createdAt: '2024-01-17T07:00:00Z',
            updatedAt: '2024-01-17T15:30:00Z',
        },
        {
            orderId: 4,
            driverId: 10,
            sellerId: 2,
            pickupAddress: '45 Awolowo Road, Ikoyi, Lagos',
            deliveryAddress: '56 Adeola Odeku Street, Victoria Island, Lagos',
            pickupContactName: 'Adebayo Fashola',
            pickupContactPhone: '+2348012345678',
            deliveryContactName: 'Tunde Williams',
            deliveryContactPhone: '+2348065432109',
            status: 'en_route_to_delivery',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task4_photo1.jpg',
                'https://storage.example.com/pickup/task4_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_004_JKL012',
            pickupVerifiedAt: '2024-01-18T09:20:00Z',
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-18T08:00:00Z',
            updatedAt: '2024-01-18T09:20:00Z',
        },
        {
            orderId: 5,
            driverId: 9,
            sellerId: 3,
            pickupAddress: '23 Zoo Road, Kano Municipal, Kano',
            deliveryAddress: '89 Ahmadu Bello Way, Kano',
            pickupContactName: 'Ibrahim Musa',
            pickupContactPhone: '+2348023456789',
            deliveryContactName: 'Aisha Bello',
            deliveryContactPhone: '+2348054321098',
            status: 'en_route_to_delivery',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task5_photo1.jpg',
                'https://storage.example.com/pickup/task5_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_005_MNO345',
            pickupVerifiedAt: '2024-01-19T10:00:00Z',
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-19T08:30:00Z',
            updatedAt: '2024-01-19T10:00:00Z',
        },
        {
            orderId: 6,
            driverId: 10,
            sellerId: 4,
            pickupAddress: '67 Ring Road, Challenge, Ibadan',
            deliveryAddress: '23 Obafemi Awolowo Way, Ibadan',
            pickupContactName: 'Olusegun Adeyemi',
            pickupContactPhone: '+2348034567890',
            deliveryContactName: 'Kehinde Olajide',
            deliveryContactPhone: '+2348043210987',
            status: 'picked_up',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task6_photo1.jpg',
                'https://storage.example.com/pickup/task6_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_006_PQR678',
            pickupVerifiedAt: '2024-01-20T11:30:00Z',
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-20T09:00:00Z',
            updatedAt: '2024-01-20T11:30:00Z',
        },
        {
            orderId: 7,
            driverId: 9,
            sellerId: 2,
            pickupAddress: '45 Awolowo Road, Ikoyi, Lagos',
            deliveryAddress: '45 Opebi Road, Ikeja, Lagos',
            pickupContactName: 'Adebayo Fashola',
            pickupContactPhone: '+2348012345678',
            deliveryContactName: 'Olufunke Adebisi',
            deliveryContactPhone: '+2348032109876',
            status: 'picked_up',
            pickupVerificationPhotos: JSON.stringify([
                'https://storage.example.com/pickup/task7_photo1.jpg',
                'https://storage.example.com/pickup/task7_photo2.jpg'
            ]),
            pickupQrCode: 'QR_PICKUP_007_STU901',
            pickupVerifiedAt: '2024-01-21T10:15:00Z',
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-21T08:45:00Z',
            updatedAt: '2024-01-21T10:15:00Z',
        },
        {
            orderId: 8,
            driverId: 10,
            sellerId: 3,
            pickupAddress: '23 Zoo Road, Kano Municipal, Kano',
            deliveryAddress: '12 Murtala Mohammed Way, Kaduna',
            pickupContactName: 'Ibrahim Musa',
            pickupContactPhone: '+2348023456789',
            deliveryContactName: 'Usman Garba',
            deliveryContactPhone: '+2348021098765',
            status: 'at_pickup',
            pickupVerificationPhotos: null,
            pickupQrCode: null,
            pickupVerifiedAt: null,
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-22T07:30:00Z',
            updatedAt: '2024-01-22T09:45:00Z',
        },
        {
            orderId: 9,
            driverId: 9,
            sellerId: 4,
            pickupAddress: '67 Ring Road, Challenge, Ibadan',
            deliveryAddress: '90 Bodija Market Road, Ibadan',
            pickupContactName: 'Olusegun Adeyemi',
            pickupContactPhone: '+2348034567890',
            deliveryContactName: 'Blessing Okoro',
            deliveryContactPhone: '+2348010987654',
            status: 'at_pickup',
            pickupVerificationPhotos: null,
            pickupQrCode: null,
            pickupVerifiedAt: null,
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-23T08:00:00Z',
            updatedAt: '2024-01-23T10:20:00Z',
        },
        {
            orderId: 10,
            driverId: 10,
            sellerId: 2,
            pickupAddress: '45 Awolowo Road, Ikoyi, Lagos',
            deliveryAddress: '67 Herbert Macaulay Way, Yaba, Lagos',
            pickupContactName: 'Adebayo Fashola',
            pickupContactPhone: '+2348012345678',
            deliveryContactName: 'Mohammed Abdullahi',
            deliveryContactPhone: '+2348009876543',
            status: 'assigned',
            pickupVerificationPhotos: null,
            pickupQrCode: null,
            pickupVerifiedAt: null,
            deliverySignature: null,
            deliveryPhotos: null,
            deliveryVerifiedAt: null,
            createdAt: '2024-01-24T07:00:00Z',
            updatedAt: '2024-01-24T07:00:00Z',
        },
    ];

    await db.insert(deliveryTasks).values(sampleDeliveryTasks);
    
    console.log('✅ Delivery tasks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});