import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Seller ID 2 Products (7 products)
        {
            sellerId: 2,
            productName: 'Premium Yellow Maize',
            productType: 'grains',
            quantity: 500,
            pricePerUnit: '450.00',
            totalPrice: '225000.00',
            status: 'available',
            listNumber: 1,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'White Rice (Local)',
            productType: 'grains',
            quantity: 300,
            pricePerUnit: '850.00',
            totalPrice: '255000.00',
            status: 'available',
            listNumber: 2,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'Fresh Tomatoes',
            productType: 'vegetables',
            quantity: 800,
            pricePerUnit: '350.00',
            totalPrice: '280000.00',
            status: 'available',
            listNumber: 3,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'White Garri',
            productType: 'processed',
            quantity: 600,
            pricePerUnit: '420.00',
            totalPrice: '252000.00',
            status: 'available',
            listNumber: 4,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'Palm Oil (Pure Red)',
            productType: 'oils',
            quantity: 200,
            pricePerUnit: '1200.00',
            totalPrice: '240000.00',
            status: 'available',
            listNumber: 5,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'Groundnut (Shelled)',
            productType: 'nuts',
            quantity: 400,
            pricePerUnit: '650.00',
            totalPrice: '260000.00',
            status: 'pending',
            listNumber: 6,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            sellerId: 2,
            productName: 'Ripe Plantain',
            productType: 'fruits',
            quantity: 1000,
            pricePerUnit: '280.00',
            totalPrice: '280000.00',
            status: 'available',
            listNumber: 7,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },

        // Seller ID 3 Products (7 products)
        {
            sellerId: 3,
            productName: 'Yam Tubers (Medium Size)',
            productType: 'tubers',
            quantity: 250,
            pricePerUnit: '1500.00',
            totalPrice: '375000.00',
            status: 'available',
            listNumber: 1,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Brown Beans (Oloyin)',
            productType: 'grains',
            quantity: 450,
            pricePerUnit: '750.00',
            totalPrice: '337500.00',
            status: 'available',
            listNumber: 2,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Big Onions (Red)',
            productType: 'vegetables',
            quantity: 700,
            pricePerUnit: '380.00',
            totalPrice: '266000.00',
            status: 'available',
            listNumber: 3,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Yellow Garri',
            productType: 'processed',
            quantity: 550,
            pricePerUnit: '480.00',
            totalPrice: '264000.00',
            status: 'available',
            listNumber: 4,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Egusi Seeds (Melon)',
            productType: 'seeds',
            quantity: 350,
            pricePerUnit: '850.00',
            totalPrice: '297500.00',
            status: 'available',
            listNumber: 5,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Sweet Potato',
            productType: 'tubers',
            quantity: 600,
            pricePerUnit: '420.00',
            totalPrice: '252000.00',
            status: 'pending',
            listNumber: 6,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            sellerId: 3,
            productName: 'Fresh Pepper (Ata Rodo)',
            productType: 'vegetables',
            quantity: 500,
            pricePerUnit: '480.00',
            totalPrice: '240000.00',
            status: 'available',
            listNumber: 7,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Seller ID 4 Products (6 products)
        {
            sellerId: 4,
            productName: 'Cassava Tubers (Fresh)',
            productType: 'tubers',
            quantity: 800,
            pricePerUnit: '320.00',
            totalPrice: '256000.00',
            status: 'available',
            listNumber: 1,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            sellerId: 4,
            productName: 'Millet (Pearl)',
            productType: 'grains',
            quantity: 400,
            pricePerUnit: '550.00',
            totalPrice: '220000.00',
            status: 'available',
            listNumber: 2,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            sellerId: 4,
            productName: 'Garden Eggs (Green)',
            productType: 'vegetables',
            quantity: 650,
            pricePerUnit: '320.00',
            totalPrice: '208000.00',
            status: 'available',
            listNumber: 3,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 4,
            productName: 'Groundnut Oil (Pure)',
            productType: 'oils',
            quantity: 150,
            pricePerUnit: '1800.00',
            totalPrice: '270000.00',
            status: 'available',
            listNumber: 4,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            sellerId: 4,
            productName: 'Fresh Okra',
            productType: 'vegetables',
            quantity: 750,
            pricePerUnit: '280.00',
            totalPrice: '210000.00',
            status: 'available',
            listNumber: 5,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            sellerId: 4,
            productName: 'Ripe Banana (Bunch)',
            productType: 'fruits',
            quantity: 900,
            pricePerUnit: '250.00',
            totalPrice: '225000.00',
            status: 'pending',
            listNumber: 6,
            photos: '[]',
            videos: '[]',
            verifiedBy: null,
            verifiedAt: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});