import { db } from '@/db';
import { users } from '@/db/schema';

async function main() {
    console.log('Seeding users table...');
    
    const sampleUsers = [
        {
            role: 'admin',
            phoneNumber: '+2348012345678',
            pin: '1234',
            email: 'chukwuemeka.okonkwo@farmconnect.ng',
            fullName: 'Chukwuemeka Okonkwo',
            middleName: 'Chibuike',
            gender: 'male',
            dateOfBirth: '1985-03-15',
            address: '45 Allen Avenue, Ikeja, Lagos',
            location: 'Lagos',
            bankAccountNumber: '0123456789',
            bankAccountName: 'Chukwuemeka Okonkwo',
            bankName: 'GTBank',
            education: 'Bachelor of Science in Computer Science',
            nin: '12345678901',
            bvn: '22334455667',
            maritalStatus: 'married',
            hasVehicle: 1,
            lineMark: 'Scar on left arm',
        },
        {
            role: 'admin',
            phoneNumber: '+2347061234567',
            pin: '9876',
            email: 'amaka.nwosu@farmconnect.ng',
            fullName: 'Amaka Nwosu',
            middleName: 'Chiamaka',
            gender: 'female',
            dateOfBirth: '1988-07-22',
            address: '12 Wuse II, Abuja',
            location: 'Abuja',
            bankAccountNumber: '9876543210',
            bankAccountName: 'Amaka Nwosu',
            bankName: 'Zenith Bank',
            education: 'Master of Business Administration',
            nin: '98765432109',
            bvn: '11223344556',
            maritalStatus: 'single',
            hasVehicle: 1,
            lineMark: 'Birthmark on right shoulder',
        },
        {
            role: 'seller',
            phoneNumber: '+2348023456789',
            pin: '2468',
            email: 'ibrahim.mohammed@gmail.com',
            fullName: 'Ibrahim Mohammed',
            middleName: 'Suleiman',
            gender: 'male',
            dateOfBirth: '1980-11-05',
            address: '23 Bompai Road, Kano',
            location: 'Kano',
            bankAccountNumber: '2345678901',
            bankAccountName: 'Ibrahim Mohammed',
            bankName: 'First Bank',
            education: 'Secondary School Certificate',
            nin: '23456789012',
            bvn: '33445566778',
            maritalStatus: 'married',
            hasVehicle: 0,
            lineMark: 'None',
        },
        {
            role: 'seller',
            phoneNumber: '+2348134567890',
            pin: '3579',
            email: 'fatima.abubakar@yahoo.com',
            fullName: 'Fatima Abubakar',
            middleName: 'Zainab',
            gender: 'female',
            dateOfBirth: '1992-04-18',
            address: '78 Independence Way, Kaduna',
            location: 'Kaduna',
            bankAccountNumber: '3456789012',
            bankAccountName: 'Fatima Abubakar',
            bankName: 'Access Bank',
            education: 'National Diploma in Agriculture',
            nin: '34567890123',
            bvn: '44556677889',
            maritalStatus: 'married',
            hasVehicle: 0,
            lineMark: 'Mole on left cheek',
        },
        {
            role: 'seller',
            phoneNumber: '+2348045678901',
            pin: '7531',
            email: 'adebayo.oluwole@farmconnect.ng',
            fullName: 'Adebayo Oluwole',
            middleName: 'Babatunde',
            gender: 'male',
            dateOfBirth: '1975-09-30',
            address: '56 Ring Road, Ibadan',
            location: 'Ibadan',
            bankAccountNumber: '4567890123',
            bankAccountName: 'Adebayo Oluwole',
            bankName: 'UBA',
            education: 'Ordinary Level Certificate',
            nin: '45678901234',
            bvn: '55667788990',
            maritalStatus: 'married',
            hasVehicle: 1,
            lineMark: 'Tribal mark on face',
        },
        {
            role: 'buyer',
            phoneNumber: '+2348038523883',
            pin: '5678',
            email: 'oluwaseun.adeyemi@gmail.com',
            fullName: 'Oluwaseun Adeyemi',
            middleName: 'Ayomide',
            gender: 'male',
            dateOfBirth: '1990-06-12',
            address: '89 Victoria Island, Lagos',
            location: 'Lagos',
            bankAccountNumber: '5678901234',
            bankAccountName: 'Oluwaseun Adeyemi',
            bankName: 'GTBank',
            education: 'Bachelor of Arts in Hospitality Management',
            nin: '56789012345',
            bvn: '66778899001',
            maritalStatus: 'single',
            hasVehicle: 1,
            lineMark: 'Tattoo on right arm',
        },
        {
            role: 'buyer',
            phoneNumber: '+2347089012345',
            pin: '8642',
            email: 'ngozi.eze@restaurant.ng',
            fullName: 'Ngozi Eze',
            middleName: 'Chioma',
            gender: 'female',
            dateOfBirth: '1987-02-28',
            address: '34 Trans-Amadi, Port Harcourt',
            location: 'Port Harcourt',
            bankAccountNumber: '6789012345',
            bankAccountName: 'Ngozi Eze',
            bankName: 'Zenith Bank',
            education: 'Higher National Diploma in Food Technology',
            nin: '67890123456',
            bvn: '77889900112',
            maritalStatus: 'married',
            hasVehicle: 1,
            lineMark: 'None',
        },
        {
            role: 'buyer',
            phoneNumber: '+2348190123456',
            pin: '1357',
            email: 'emeka.okafor@market.com',
            fullName: 'Emeka Okafor',
            middleName: 'Chinedu',
            gender: 'male',
            dateOfBirth: '1983-12-08',
            address: '67 Ogui Road, Enugu',
            location: 'Enugu',
            bankAccountNumber: '7890123456',
            bankAccountName: 'Emeka Okafor',
            bankName: 'First Bank',
            education: 'Bachelor of Science in Business Administration',
            nin: '78901234567',
            bvn: '88990011223',
            maritalStatus: 'married',
            hasVehicle: 1,
            lineMark: 'Scar on forehead',
        },
        {
            role: 'driver',
            phoneNumber: '+2348056789012',
            pin: '9753',
            email: 'yusuf.garba@logistics.ng',
            fullName: 'Yusuf Garba',
            middleName: 'Abubakar',
            gender: 'male',
            dateOfBirth: '1995-08-14',
            address: '101 Ahmadu Bello Way, Abuja',
            location: 'Abuja',
            bankAccountNumber: '8901234567',
            bankAccountName: 'Yusuf Garba',
            bankName: 'Access Bank',
            education: 'Senior Secondary School Certificate',
            nin: '89012345678',
            bvn: '99001122334',
            maritalStatus: 'single',
            hasVehicle: 1,
            lineMark: 'Birthmark on neck',
        },
        {
            role: 'driver',
            phoneNumber: '+2347012345678',
            pin: '4321',
            email: 'tunde.williams@delivery.ng',
            fullName: 'Tunde Williams',
            middleName: 'Adekunle',
            gender: 'male',
            dateOfBirth: '1991-05-20',
            address: '28 Apapa Road, Lagos',
            location: 'Lagos',
            bankAccountNumber: '9012345678',
            bankAccountName: 'Tunde Williams',
            bankName: 'UBA',
            education: 'National Certificate in Education',
            nin: '90123456789',
            bvn: '00112233445',
            maritalStatus: 'single',
            hasVehicle: 1,
            lineMark: 'None',
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Users seeder failed:', error);
    process.exit(1);
});